#!/usr/bin/env ruby
#encoding: utf-8

require "excel_diff"

case ARGV.size
when 2
  exit(1) unless ExcelDiff::UsingGit.show(ARGV[0], ARGV[1])
when 1
  exit(1) unless ExcelDiff::UsingGit.show(ARGV[0])
else
  puts '引数を確認してください'
  puts '$ excel_git_diff file'
end
