#!/usr/bin/env ruby
#encoding: utf-8

require "excel_diff"
require "optparse"

opt = OptionParser.new
options = {}

opt.on('-n num', Integer) { |v| options[:n] = v }
opt.on('-m num2', Integer) { |v| options[:n2] = v }

opt.parse!(ARGV)
p options
p ARGV

case ARGV.size
when 0, 1
  puts '比較するファイル名を指定してください。'
  puts '$ excel_diff file1 file2 [-n num]'
  exit
when 2
  status = true

  excel1 = ExcelDiff.excel_parse(ARGV[0])
  excel2 = ExcelDiff.excel_parse(ARGV[1])

  if options[:n].nil?
    status = ExcelDiff.all_sheet_diff(excel1, excel2)
    # status = ExcelDiff.all_sheet_diff(excel1, excel2, using: 'diffy')
  else
    status = ExcelDiff.sheet_diff(excel1, excel2, options[:n], n2: options[:n2])
    # ExcelDiff.sheet_diff(excel1, excel2, options[:n], using: 'diffy')
  end

  exit(1) unless status
else
  puts '引数が多すぎます。'
end
